### ISSUE TITLE
KV Cache/Environment in wrangler/config Files

### ISSUE THREAD

**Issue by TugT4G** [stephan13360/cloudflare-worker#1]
Thanks for posting this! I'm sure you could totally make this even better by adding an environment and enabling KV cache to store cached content for faster delivery. Specify the environment in the wrangler.toml file and enable KV cache in the config file then publish the environment. I'm going to give it a go tomorrow. What do you think?

**Comment by TugT4G** [comment]
So I tried it out and It did not work as I thought. There May be more configuration needed but it's above my scope of skill set.

**Comment by stephan13360** [comment]
I don't think using the kv store would improve delivery time. But it could increase the cache hit ratio. Delivering from the cloudflare cache (what this worker does) is probably a little bit faster than from the kv store, but the cache is only available at one POP. So if you have users coming from all ober the world, you could use the kv store to load the cache in other POPs.

1. Worker looks if request is in the cache in this POP
2. If not, get request answer from kv store if its recent enough
3. If kv store is empty for this request or to old: contact origin

But I have not yet used the kv store, so I can't help you there.
There is however an example worker from cloudflare, that uses the kv store to cache html sites. Maybe this can help you: https://github.com/cloudflare/worker-examples/blob/master/examples/edge-cache-html/README.md
